### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by OBJ-feye** [congqiu/yapi-plugin-auto-test#1]
yapi 1.9.2
node：v12.18.3
os：centos 7.5

> dtrace-provider@0.8.8 install /home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
gyp ERR! System Linux 4.19.8-1.el7.elrepo.x86_64
gyp ERR! command "/data/inphase/nodejs/node-v12.18.3-linux-x64/bin/node" "/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider/suppress-error.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

> ghooks@2.0.4 install /home/tb_zhangyl/my-yapi/vendors/node_modules/ghooks
> node ./bin/module-install

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/tb_zhangyl/my-yapi/vendors/node_modules/ghooks/bin/module-install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN markdown-it-include@1.1.1 requires a peer of markdown-it@>=8.4.2 <11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.8 (node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.8 install: `node-gyp rebuild || node suppress-error.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghooks@2.0.4 install: `node ./bin/module-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ghooks@2.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-11T00_47_58_014Z-debug.log
安装插件成功
正在安装依赖...

> dtrace-provider@0.8.8 install /home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
gyp ERR! System Linux 4.19.8-1.el7.elrepo.x86_64
gyp ERR! command "/data/inphase/nodejs/node-v12.18.3-linux-x64/bin/node" "/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/tb_zhangyl/my-yapi/vendors/node_modules/dtrace-provider/suppress-error.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

> ghooks@2.0.4 install /home/tb_zhangyl/my-yapi/vendors/node_modules/ghooks
> node ./bin/module-install

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/tb_zhangyl/my-yapi/vendors/node_modules/ghooks/bin/module-install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN markdown-it-include@1.1.1 requires a peer of markdown-it@>=8.4.2 <11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.8 (node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.8 install: `node-gyp rebuild || node suppress-error.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghooks@2.0.4 install: `node ./bin/module-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ghooks@2.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-11T00_48_17_123Z-debug.log
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'yapi-plugin-auto-test'
Require stack:
- /home/tb_zhangyl/my-yapi/vendors/common/plugin.js
- /home/tb_zhangyl/my-yapi/vendors/ykit.config.js
- /data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/models/Project.js
- /data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/modules/manager.js
- /data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/cli.js
- /data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/bin/ykit
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getPluginConfig (/home/tb_zhangyl/my-yapi/vendors/common/plugin.js:8:20)
    at /home/tb_zhangyl/my-yapi/vendors/common/plugin.js:39:22
    at Array.map (<anonymous>)
    at Object.exports.initPlugins (/home/tb_zhangyl/my-yapi/vendors/common/plugin.js:33:21)
    at initPlugins (/home/tb_zhangyl/my-yapi/vendors/ykit.config.js:42:30)
    at Object.<anonymous> (/home/tb_zhangyl/my-yapi/vendors/ykit.config.js:61:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tb_zhangyl/my-yapi/vendors/common/plugin.js',
    '/home/tb_zhangyl/my-yapi/vendors/ykit.config.js',
    '/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/models/Project.js',
    '/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/modules/manager.js',
    '/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/lib/cli.js',
    '/data/inphase/nodejs/node-v12.18.3-linux-x64/lib/node_modules/ykit/bin/ykit'
  ]
}

**Comment by congqiu** [comment]
看报错应该是其他的模块安装有报错，可以尝试再次安装或者直接安装
